# Generated by CodiumAI
import pytest

from pycfr.models import BetSizeCandidates, BetSizeType


class TestBetSizeCandidates:
    # Test that the BetSizeCandidates object is initialized correctly when provided with valid bet_str and raise_str
    def test_initialize_with_valid_strings(self):
        bet_str = "2x,3c,4e,5%,a"
        raise_str = "6x,7c,8e,9%,a"
        bet_size_candidates = BetSizeCandidates(bet_str, raise_str)

        assert len(bet_size_candidates.list_bet_size) == 5
        assert len(bet_size_candidates.list_raise_size) == 5

        assert bet_size_candidates.list_bet_size[0].type == BetSizeType.PrevBetRelative
        assert bet_size_candidates.list_bet_size[0].value == 2.0

        assert bet_size_candidates.list_bet_size[1].type == BetSizeType.Additive
        assert bet_size_candidates.list_bet_size[1].value == 3

        assert bet_size_candidates.list_bet_size[2].type == BetSizeType.Geometric
        assert bet_size_candidates.list_bet_size[2].value == (4, float("inf"))

        assert bet_size_candidates.list_bet_size[3].type == BetSizeType.PotRelative
        assert bet_size_candidates.list_bet_size[3].value == 5.0

        assert bet_size_candidates.list_bet_size[4].type == BetSizeType.AllIn
        assert bet_size_candidates.list_bet_size[4].value is None

        assert bet_size_candidates.list_raise_size[0].type == BetSizeType.PrevBetRelative
        assert bet_size_candidates.list_raise_size[0].value == 6.0

        assert bet_size_candidates.list_raise_size[1].type == BetSizeType.Additive
        assert bet_size_candidates.list_raise_size[1].value == 7

        assert bet_size_candidates.list_raise_size[2].type == BetSizeType.Geometric
        assert bet_size_candidates.list_raise_size[2].value == (8, float("inf"))

        assert bet_size_candidates.list_raise_size[3].type == BetSizeType.PotRelative
        assert bet_size_candidates.list_raise_size[3].value == 9.0

        assert bet_size_candidates.list_raise_size[4].type == BetSizeType.AllIn
        assert bet_size_candidates.list_raise_size[4].value is None
